# Generated by Django 3.0.2 on 2020-04-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('balance', models.FloatField()),
                ('last_transaction', models.DateTimeField(default=None)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp_tracker.User')),
            ],
        ),
        migrations.CreateModel(
            name='Transcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(max_length=10)),
                ('transaction_details', models.TextField()),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp_tracker.User')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp_tracker.Wallet')),
            ],
        ),
    ]
