# Generated by Django 3.0.2 on 2020-04-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='last_transaction',
        ),
    ]
