# Generated by Django 3.0.2 on 2020-04-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_tracker', '0002_remove_wallet_last_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcation',
            name='transaction_time',
            field=models.DateTimeField(),
        ),
    ]
